{
  "version": "1.1.1",
  "author": "Hattmo",
  "license": "GPL-3.0-or-later",
  "name": "@hattmo/tryagain",
  "description": "Retrys code that can throw an exception N number of times.",
  "scripts": {
    "test": "cross-per-env",
    "test:staging": "mocha -r ts-node/register ./test/**/*Test.ts",
    "test:development": "mocha -r ts-node/register --bail ./test/**/*Test.ts",
    "build": "tsc --project .",
    "prepublish": "npm run build"
  },
  "main": "./dist/index.js",
  "devDependencies": {
    "@types/chai": "^4.2.18",
    "@types/mocha": "^8.2.2",
    "@types/node": "^15.6.0",
    "@types/sinon": "^10.0.0",
    "chai": "^4.3.4",
    "cross-per-env": "^1.0.5",
    "mocha": "^8.4.0",
    "sinon": "^10.0.0",
    "ts-node": "^9.1.1",
    "tslint": "^5.20.1",
    "typescript": "^4.2.4"
  }
}
